geometry_msgs/PointStamped point
string target_frame
duration timeout # How log to wait for this transform

# More advanced lookup (time travel)
time target_time
string fixed_frame
---
geometry_msgs/PointStamped point
string error_msg
